# Android project include wrapper for the mobile gameplay UI pass.
# Keep the existing compatibility/lifecycle patches, then apply the current
# Android layout/input fixes once to OpenBoE's source before it is compiled.
include("${CMAKE_CURRENT_LIST_DIR}/android_project_include.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v3.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v4.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v5.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v5_compilefix.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v6.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v7.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v8.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v9.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v10.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v11_anchorfix.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v11.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v12.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v13.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v14.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v15.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v16_scriptfix.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v16.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v17.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/android_mobile_ui_fixes_v18.cmake")
